### ISSUE TITLE
Config setting to shift reroll button above list.

### ISSUE THREAD

**Issue by irunatbullets** [Draylar/reroll#13]
In AOF3 there is a persistent inventory sorting button (added by charm I think) which overlaps the reroll button.

![unknown](https://user-images.githubusercontent.com/344908/119467998-57015e80-bd46-11eb-9095-5316f4fdd3c3.png)

I'm wondering if you could add an option to shift the re-roll button above the enchants list?

**Comment by riverbanksquid** [comment]
This has been bugging me, too! I can confirm that the conflicting button is added by Charm. Having a way to configure x and y offset for Reroll's button (like Hide Armor has, for example) would be huge. The only solution at the moment is to disable Charm's "inventory tidying" module and install a different inventory sorting mod.

**Comment by Draylar** [comment]
Just added a config option to move the icon above the enchanting list in the latest version - let me know how it works out :)
