### ISSUE TITLE
Tooltip displays in background

### ISSUE THREAD

**Issue by Wdavery** [Draylar/reroll#14]
When using with [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) the tooltip displays behind the REI icons. I haven't seen this happen with any tooltip before.

Regular tooltip: ![2021-05-27_08 56 54](https://user-images.githubusercontent.com/12989893/119829775-9d32fb00-bec9-11eb-85cb-125e32fcd504.png)
Reroll tooltip:
![2021-05-27_08 56 59](https://user-images.githubusercontent.com/12989893/119829771-9ad0a100-bec9-11eb-9d0d-9a2c7d1f69ce.png)

**Comment by SalvieMundi** [comment]
I have provided a release until Draylar has time to accept the pull request.
https://github.com/SalvieMundi/reroll/releases/tag/1.3.0-1.17.1
