### ISSUE TITLE
Reroll text wrong

### ISSUE THREAD

**Issue by YorbenJoosen** [Draylar/reroll#15]
In the config I changed that you need 0 lvls and 1 lapis, but it still says 1 lvl and 0 lapis after restarting the server. Just to give a heads up :)

**Comment by Draylar** [comment]
I'm having trouble reproducing this in development, so there's a chance it was fixed at some point. Please let me know if you re-encounter this issue in the future with the latest version and I will look into it again. Thanks for the report!

![image](https://user-images.githubusercontent.com/17728338/132266764-6c5b2e0d-50da-45b6-86b9-69978d16fac6.png)
