### ISSUE TITLE
Mod menu support

### ISSUE THREAD

**Issue by SylisMC** [Draylar/reroll#6]
[Mod menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) is really awesome for changing config files on the go, and it cuts out the restart the game process when building a modpack. support for it would be genuinely awesome

**Comment by Draylar** [comment]
Thanks for the suggestion, out in 1.2.0. The only thing to note is that the client-side hover counter (that shows you what is needed) won't refresh until you restart your game after modifying values in the modmenu screen. The actual values in the config will still apply, though.
